services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8888:8888
    depends_on:
      - cockroachdb
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=cockroachdb
      - DB_PORT=26257
      - DB_NAME=simpler

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.9
    container_name: cockroachdb
    command: start-single-node --insecure
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    expose:
      - 26257
      - 8080
    ports:
      - 26257:26257
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  cockroach-data:
    driver: local
